# -*- coding: utf-8 -*-
"""iris_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yj6XnQq_gPPzJ8U-a04Yke6AGRUICNY8
"""

# ===============================
# IRIS FLOWER CLASSIFICATION
# ===============================

import pandas as pd
import matplotlib.pyplot as plt

# 1. Load Dataset (built-in)
from sklearn.datasets import load_iris

iris = load_iris()

X = iris.data
y = iris.target

# Convert to DataFrame (optional but cleaner)
df = pd.DataFrame(X, columns=iris.feature_names)
df['species'] = y

print(df.head())


# 2. Train-Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


# 3. Train Model (KNN)
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)


# 4. Predict
y_pred = model.predict(X_test)


# 5. Evaluate
from sklearn.metrics import accuracy_score, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


# 6. Visualization (result.png)
plt.figure()
plt.scatter(X_test[:, 0], X_test[:, 1], c=y_pred)

plt.xlabel("Sepal Length")
plt.ylabel("Sepal Width")
plt.title("Iris Classification Result")

plt.savefig("result.png")
plt.show()